
# Monitors

monitorv2 {
    output = DP-1
    mode = 2560x1080@75
    position = 0x0
    scale = 1
    supports_wide_color = -1
    supports_hdr = 1
    sdr_min_luminance = 0.005
    sdr_max_luminance = 250
}

monitorv2 {
    output = DP-2
    mode = 1366x768
    position = 2560x312
    scale = 1
    supports_wide_color = -1
    supports_hdr = -1
}


# Workspaces

workspace = 1,monitor:DP-1, persistent:true
workspace = 2,monitor:DP-2, persistent:true,layout:scrolling
workspace = 3,monitor:DP-1, persistent:true
workspace = 4,monitor:DP-2, persistent:true
workspace = 5,monitor:DP-1, persistent:true
workspace = 6,monitor:DP-2, persistent:true
workspace = 7,monitor:DP-1, persistent:true
workspace = 8,monitor:DP-2, persistent:true
workspace = 9,monitor:DP-1, persistent:true
workspace = 10,monitor:DP-2, persistent:true
