#script binds
b           script-binding set_gif_start            # set the start timestamp for to make GIF (mpv-gif.lua)
B           script-binding set_gif_end              # set the stop timestamp for to make GIF (mpv-gif.lua)
ctrl+b      script-binding make_gif                 # make the GIF using start and stop timestamps (mpv-gif.lua)
