# Env variables
env = PATH,$PATH:/home/leonardo/.local/share/scripts
env = XDG_SCREENSHOTS_DIR, $HOME/Pictures/screenshots
env = ELECTRON_OZONE_PLATFORM_HINT, wayland
env = GTK_IM_MODULE, ibus

# Gaming
env = PROTON_FSR4_UPGRADE, 1
env = PROTON_FSR4_INDICATOR, 1
env = PROTON_FSR4_RDNA3_UPGRADE, 1
env = PROTON_ENABLE_WAYLAND, 1
env = PROTON_NO_WM_DECORATION, 1
env = PROTON_ENABLE_HDR, 1
# env = PROTON_USE_NTSYNC, 1
# env = PROTON_ENABLE_MESA_ANTI_LAG, 1

# Input
input {
    kb_layout = br,us
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = -0.5
    force_no_accel = 0

    numlock_by_default = 1
}

# Misc
misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

xwayland {
    force_zero_scaling = true
}

render {
    cm_fs_passthrough = 1
    cm_auto_hdr = 1
  }
