# Window rules
windowrule = workspace special,match:class ^(spotify)$

windowrule = float true,match:class ^(mpv)$
windowrule = center true,match:class ^(mpv)$
windowrule = workspace 5,match:class ^(mpv)$
