backend = "kmeans"
color_space = "lch"
palette = "ansidark"
fallback_generator = "complementary"

[templates]
  temp.template = 'temp.template'
  temp.target = '~/.config/wallust/templates/temp.target'
 
  hyprlock.template = 'hyprlock.colors'
  hyprlock.target = '~/.config/hypr/resources/colors.conf'

  hyprland.template = 'hyprland.colors'
  hyprland.target = '~/.config/hypr/colors.conf'

  waybar.template = 'waybar.colors'
  waybar.target = '~/.config/waybar/colors.css'
 
  fuzzel.template = 'fuzzel.colors'
  fuzzel.target = '~/.config/fuzzel/colors.ini'
  
  kitty.template = 'kitty.colors'
  kitty.target = '~/.config/kitty/colors.conf'
