backend = "wal"
threshold = 10
color_space = "lch"
palette = "dark16"

[templates]
  temp.template = 'templates/temp.template'
  temp.target = '~/.config/wallust/templates/temp.target'
  
  hyprlock.template = 'templates/hyprlock.colors'
  hyprlock.target = '~/.config/hypr/resources/colors.conf'

  hyprland.template = 'templates/hyprland.colors'
  hyprland.target = '~/.config/hypr/hyprcolors.conf'

  waybar.template = 'templates/waybar.colors'
  waybar.target = '~/.config/waybar/colors.css'
