backend = "wal"
color_space = "lch"
palette = "ansidark"

[templates]
  temp.template = 'temp.template'
  temp.target = '~/.config/wallust/templates/temp.target'
  
  hyprlock.template = 'hyprlock.colors'
  hyprlock.target = '~/.config/hypr/resources/colors.conf'

  hyprland.template = 'hyprland.colors'
  hyprland.target = '~/.config/hypr/colors.conf'

  waybar.template = 'waybar.colors'
  waybar.target = '~/.config/waybar/colors.css'
