## General
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

shell = "/usr/bin/fish"
live_config_reload = true

[window]
  padding = { x = 10, y = 10 }
  decorations = "Full"
  opacity = 0.85
  blur = true
  startup_mode = "Maximized"

[font]
  normal = { family = "CaskaydiaMono Nerd Font", style = "Regular"}
  bold = { family = "CaskaydiaMono Nerd Font", style = "Bold"}
  italic = { family = "CaskaydiaMono Nerd Font", style = "Italic"}
  bold_italic = { family = "CaskaydiaMono Nerd Font", style = "Bold Italic"}
  size = 10

[cursor]
  style = { shape = "Beam", blinking = "On" }
